[package]
name = "rash_derive"
version = "0.1.0"
authors = ["Pando85 <pando855@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

[features]
default = ["syn/full"]
