[package]
name = "rash_core"
version = "0.1.0"
authors = ["Pando85 <pando855@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rash_derive = { path = "../rash_derive" }
env_logger = "0.7.0"
lazy_static = "1.4.0"
log = "0.4"
serde_json = "1.0"
yaml-rust = "0.4"

[dev-dependencies]
tempfile = "3"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt"]
