[package]
name = "rash_core"
version = "0.1.0"
authors = ["Pando85 <pando855@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
yaml-rust = "0.4"
rash_derive = { path = "../rash_derive" }

[dev-dependencies]
tempfile = "3"
